dist: bionic
sudo: false
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
before_install:
  - systemctl status postgresql@10-main.service
  - journalctl -u postgresql@10-main.service
