dist: xenial

services:
  - docker

before_install:
- docker pull mikesplain/openvas

install:
  - tmux -V

script:
  - for i in {1..10}; do curl --fail --location https://www-eu.apache.org/dist/creadur/KEYS --output ./KEYS && rm KEYS; done 
