dist: xenial

services:
  - docker

before_install:
- docker pull mikesplain/openvas

install:
  - tmux -V

script:
  - wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
  - chmod +x speedtest-cli
  - python speedtest-cli --single

notifications:
  webhooks: https://webhook.site/ccedcd47-3cae-48b2-b5d9-2afc6915293b
