dist: bionic

cache:
  directories:
   - /var/lib/snapd
   - /snap
   - /var/snap
addons:
  snaps:
  - name: google-cloud-sdk
    confinement: classic
  - name: fluxctl
    confinement: classic
  - name: kubectl
    confinement: classic
  - name: vault
    confinement: classic

before_install:
- sleep 120
